//
//  FlexterAnalyticsEvents.h
//  flexter
//
//  Created by Anurag Tolety on 11/3/14.
//  Copyright (c) 2014 JMJ Innovations. All rights reserved.
//

#ifndef flexter_FlexterAnalyticsEvents_h
#define flexter_FlexterAnalyticsEvents_h

#define FLEXTER_ANALYTICS_EVENT_WORKOUT_VIEWING_STARTED @"WorkoutViewingStarted"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_VIEWING_ENDED @"WorkoutViewingEnded"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_STARTED @"WorkoutStarted"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_ENDED @"WorkoutEnded"
#define FLEXTER_ANALYTICS_EVENT_PUSH_SELECTED_AFTER_WORKOUT @"PushSelectedAfterWorkout"
#define FLEXTER_ANALYTICS_EVENT_PUSH_SELECTED_IN_SETTINGS @"PushSelectedInSettings"
#define FLEXTER_ANALYTICS_EVENT_PUSH_REJECTED @"PushRejected"
#define FLEXTER_ANALYTICS_EVENT_PARSE_REJECTED @"ParseRejected"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_TYPE_SELECTED @"WorkoutTypeSelected"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_SELECTED @"WorkoutSelected"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_COMPLETED @"WorkoutCompleted"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_SCROLLED @"WorkoutScrolled"
#define FLEXTER_ANALYTICS_EVENT_EXERCISE_SELECTED @"ExerciseSelected"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_SEE_MORE_SELECTED @"WorkoutSeeMoreSelected"
#define FLEXTER_ANALYTICS_EVENT_WORKOUT_SEE_LESS_SELECTED @"WorkoutSeeLessSelected"
#define FLEXTER_ANALYTICS_EVENT_EXERCISE_TIMER_STARTED @"ExerciseTimerStarted"
#define FLEXTER_ANALYTICS_EVENT_EXERCISE_TIMER_ENDED @"ExerciseTimerEnded"
#define FLEXTER_ANALYTICS_EVENT_EXERCISE_TIMER_RESET @"ExerciseTimerReset"
#define FLEXTER_ANALYTICS_EVENT_EXERCISE_CHECKED @"ExerciseChecked"
#define FLEXTER_ANALYTICS_EVENT_SETTINGS_OPENED @"SettingsOpened"
#define FLEXTER_ANALYTICS_EVENT_PARAM_OBJECT_ID @"ObjectId"
#define FLEXTER_ANALYTICS_EVENT_PARAM_WORKOUT_TYPE @"WorkoutType"
#define FLEXTER_ANALYTICS_EVENT_PARAM_PUSH_TYPE @"PushType"

#define PARSE_REQUEST_LIMIT_EXCEEDED_CODE 155

#endif
